[supabase]
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3YmlsZmdia2xxa2F3amVuZHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMxMDk2MTksImV4cCI6MjAzODY4NTYxOX0.nPrso4gC5cbLdIA2kuF-Lj1nXKC6phBPBZTZ0oZhyPo"
supabase_url = "https://lwbilfgbklqkawjendxe.supabase.co"
